services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: technical_test_postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks:
      - symfony_network

  backend:
    build:
      context: ./backend
      dockerfile: ./backend.Dockerfile
    container_name: technical_test_symfony
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: ${TARGET}
      DATABASE_URL: postgresql://postgres:postgres@db:5432/app?serverVersion=16&charset=utf8
    depends_on:
      - db
    networks:
      - symfony_network
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: technical_test_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - backend
    networks:
      - symfony_network

volumes:
  database_data:

networks:
  symfony_network:
    driver: bridge